In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

In [35]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [37]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [38]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [39]:
df = pd.get_dummies(df, columns=["fuel", "seller_type", "transmission"], drop_first=True)

In [40]:
df.head()

,name,year,selling_price,km_driven,owner,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual
0,Maruti 800 AC,2007,60000,70000,First Owner,False,False,False,True,True,False,True
1,Maruti Wagon R LXI Minor,2007,135000,50000,First Owner,False,False,False,True,True,False,True
2,Hyundai Verna 1.6 SX,2012,600000,100000,First Owner,True,False,False,False,True,False,True
3,Datsun RediGO T Option,2017,250000,46000,First Owner,False,False,False,True,True,False,True
4,Honda Amaze VX i-DTEC,2014,450000,141000,Second Owner,True,False,False,False,True,False,True

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   name                          4340 non-null   object
 1   year                          4340 non-null   int64
 2   selling_price                 4340 non-null   int64
 3   km_driven                     4340 non-null   int64
 4   owner                         4340 non-null   object
 5   fuel_Diesel                   4340 non-null   bool
 6   fuel_Electric                 4340 non-null   bool
 7   fuel_LPG                      4340 non-null   bool
 8   fuel_Petrol                   4340 non-null   bool
 9   seller_type_Individual        4340 non-null   bool
 10  seller_type_Trustmark Dealer  4340 non-null   bool
 11  transmission_Manual           4340 non-null   bool
dtypes: bool(7), int64(3), object(2)
memory usage: 199.3+ KB

In [42]:
#Marka
df['Brand'] = df['name'].apply(lambda x: x.split()[0])

#Model
df['Model'] = df['name'].apply(lambda x: x.split()[1])

#Paket ve yoksa kontrol
df['Package'] = df['name'].apply(lambda x: x.split()[2] if len(x.split()) > 2 else "Standart")

print(df)

                                     name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000
1                Maruti Wagon R LXI Minor  2007         135000      50000
2                    Hyundai Verna 1.6 SX  2012         600000     100000
3                  Datsun RediGO T Option  2017         250000      46000
4                   Honda Amaze VX i-DTEC  2014         450000     141000
...                                   ...   ...            ...        ...
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000
4337                  Maruti 800 AC BSIII  2009         110000      83000
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000
4339                     Renault KWID RXT  2016         225000      40000

             owner  fuel_Diesel  fuel_Electric  fuel_LPG  fuel_Petrol  \
0      First Owner        False          False     False         True
1      First Owner        False          False     False         True
2      First Owner         True          False     False        False
3      First Owner        False          False     False         True
4     Second Owner         True          False     False        False
...            ...          ...            ...       ...          ...
4335  Second Owner         True          False     False        False
4336  Second Owner         True          False     False        False
4337  Second Owner        False          False     False         True
4338   First Owner         True          False     False        False
4339   First Owner        False          False     False         True

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                       True                         False
1                       True                         False
2                       True                         False
3                       True                         False
4                       True                         False
...                      ...                           ...
4335                    True                         False
4336                    True                         False
4337                    True                         False
4338                    True                         False
4339                    True                         False

      transmission_Manual    Brand   Model Package
0                    True   Maruti     800      AC
1                    True   Maruti   Wagon       R
2                    True  Hyundai   Verna     1.6
3                    True   Datsun  RediGO       T
4                    True    Honda   Amaze      VX
...                   ...      ...     ...     ...
4335                 True  Hyundai     i20   Magna
4336                 True  Hyundai     i20   Magna
4337                 True   Maruti     800      AC
4338                 True  Hyundai   Creta     1.6
4339                 True  Renault    KWID     RXT

[4340 rows x 15 columns]

In [50]:
y = df["selling_price"]             # Hedef değişken (Target)
X = df.drop("selling_price", axis=1) # Fiyat hariç diğer tüm özellikler (Features)

KeyError: "['name'] not found in axis"

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   name                          4340 non-null   object
 1   year                          4340 non-null   int64
 2   selling_price                 4340 non-null   int64
 3   km_driven                     4340 non-null   int64
 4   owner                         4340 non-null   object
 5   fuel_Diesel                   4340 non-null   bool
 6   fuel_Electric                 4340 non-null   bool
 7   fuel_LPG                      4340 non-null   bool
 8   fuel_Petrol                   4340 non-null   bool
 9   seller_type_Individual        4340 non-null   bool
 10  seller_type_Trustmark Dealer  4340 non-null   bool
 11  transmission_Manual           4340 non-null   bool
 12  Brand                         4340 non-null   object
 13  Model                         4340 non-null   object
 14  Package                       4340 non-null   object
dtypes: bool(7), int64(3), object(5)
memory usage: 301.0+ KB

In [46]:
from sklearn.model_selection import train_test_split

# 1. Önce X ve y'yi ayıralım
# (selling_price hedefimiz, gerisi özellikler)
y = df["selling_price"]
X = df.drop("selling_price", axis=1)

# 2. Veriyi Train ve Test olarak bölüyoruz (%80 Eğitim, %20 Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Target Encoding yapacağımız sütunlar
encode_edilecekler = ['Brand', 'Model', 'Package']

# Döngü ile hepsini tek tek halledelim
for col in encode_edilecekler:
    # A) SADECE TRAIN setindeki ortalamaları öğreniyoruz
    # (Hangi marka ortalama ne kadar fiyata satılmış?)
    means = X_train.join(y_train).groupby(col)['selling_price'].mean()
    
    # B) Öğrendiğimiz bu ortalamaları X_train'e yazıyoruz
    X_train[col + '_Encoded'] = X_train[col].map(means)
    
    # C) Aynı ortalamaları X_test'e de uyguluyoruz (Kuralı train'den öğrendik, test'e uyguladık)
    X_test[col + '_Encoded'] = X_test[col].map(means)
    
    # D) KRİTİK NOKTA: Test setinde olup Train'de olmayan yeni bir model varsa
    # (Örneğin Train'de hiç 'Bugatti' yok ama Test'te var)
    # Orası boş (NaN) kalır. Orayı genel ortalama fiyatla dolduruyoruz.
    genel_ortalama = y_train.mean()
    X_test[col + '_Encoded'].fillna(genel_ortalama, inplace=True)
    X_train[col + '_Encoded'].fillna(genel_ortalama, inplace=True) # Garanti olsun diye
    
    # E) Artık işi biten "metin" (string) sütunlarını siliyoruz
    X_train.drop(col, axis=1, inplace=True)
    X_test.drop(col, axis=1, inplace=True)

# Sonucu görelim
print("--- İşlem Tamamlandı ---")
print("Eğitim Seti (X_train) Son Hali:")
print(X_train.head())

--- İşlem Tamamlandı ---
Eğitim Seti (X_train) Son Hali:
                                 name  year  km_driven         owner  \
227         Mahindra Scorpio S11 BSIV  2017      20000   First Owner
964            Maruti Swift Dzire VDI  2018      50000   First Owner
2045              Maruti Alto 800 LXI  2013      25000  Second Owner
1025         Chevrolet Beat Diesel LS  2011      70000   First Owner
4242  Maruti Vitara Brezza LDi Option  2017      72000   First Owner

      fuel_Diesel  fuel_Electric  fuel_LPG  fuel_Petrol  \
227          True          False     False        False
964          True          False     False        False
2045        False          False     False         True
1025         True          False     False        False
4242         True          False     False        False

      seller_type_Individual  seller_type_Trustmark Dealer  \
227                     True                         False
964                     True                         False
2045                    True                         False
1025                    True                         False
4242                   False                         False

      transmission_Manual  Brand_Encoded  Model_Encoded  Package_Encoded
227                  True  585972.266436  604291.597222     1.420000e+06
964                  True  339956.287938  437309.496032     4.775849e+05
2045                 True  339956.287938  193027.382353     2.333527e+05
1025                 True  238850.564103  191076.892308     2.377870e+05
4242                 True  339956.287938  805200.000000     8.052000e+05

C:\Users\musta\AppData\Local\Temp\ipykernel_33436\2390570460.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[col + '_Encoded'].fillna(genel_ortalama, inplace=True)
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\2390570460.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[col + '_Encoded'].fillna(genel_ortalama, inplace=True) # Garanti olsun diye
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\2390570460.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[col + '_Encoded'].fillna(genel_ortalama, inplace=True)
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\2390570460.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[col + '_Encoded'].fillna(genel_ortalama, inplace=True) # Garanti olsun diye
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\2390570460.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[col + '_Encoded'].fillna(genel_ortalama, inplace=True)
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\2390570460.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[col + '_Encoded'].fillna(genel_ortalama, inplace=True) # Garanti olsun diye

In [51]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

# 1. Veriyi En Baştan Yükle (Hata riskini sıfırla)
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

# 2. İsim Parçalama (Feature Engineering)
# "name" sütunundan yeni özellikler türetiyoruz
df['Brand'] = df['name'].apply(lambda x: x.split()[0])
df['Model'] = df['name'].apply(lambda x: x.split()[1] if len(x.split()) > 1 else "Unknown")
df['Package'] = df['name'].apply(lambda x: x.split()[2] if len(x.split()) > 2 else "Standart")

# --- KRİTİK HAMLE: "name" sütununu artık siliyoruz! ---
df.drop('name', axis=1, inplace=True)

# 3. Diğer Kategorik Verileri Sayısallaştırma
# Fuel, Seller_Type, Transmission VE Owner sütunlarını One-Hot yapıyoruz
# (Not: Owner sütununu da ekledim yoksa o da hata verirdi)
cols_to_dummy = ["fuel", "seller_type", "transmission", "owner"]
df = pd.get_dummies(df, columns=cols_to_dummy, drop_first=True)

# 4. Target Encoding Hazırlığı
X = df.drop("selling_price", axis=1)
y = df["selling_price"]

# Eğitim ve Test olarak ayır (%80 - %20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Target Encoding (Sadece Marka, Model ve Paket için)
# Bu işlem onları "ortalama fiyat gücüne" çevirecek
target_cols = ['Brand', 'Model', 'Package']

for col in target_cols:
    # Train setinden "bu özellik ne kadar ediyor?" bilgisini öğren
    means = X_train.join(y_train).groupby(col)['selling_price'].mean()
    
    # Öğrendiğini Train ve Test setine uygula
    X_train[col + '_Encoded'] = X_train[col].map(means)
    X_test[col + '_Encoded'] = X_test[col].map(means)
    
    # Eğer Test setinde olup Train'de olmayan (yeni) bir araba varsa
    # Boş kalan yerleri genel ortalama ile doldur
    X_train[col + '_Encoded'].fillna(y_train.mean(), inplace=True)
    X_test[col + '_Encoded'].fillna(y_train.mean(), inplace=True)
    
    # İşimiz biten metin sütunlarını atalım
    X_train.drop(col, axis=1, inplace=True)
    X_test.drop(col, axis=1, inplace=True)

# 6. Final: Modeli Eğit ve Test Et
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f"Başarı Skoru (R2): %{r2_score(y_test, y_pred)*100:.2f}")
print(f"Ortalama Hata (MAE): {mean_absolute_error(y_test, y_pred):,.0f} TL")

C:\Users\musta\AppData\Local\Temp\ipykernel_33436\3721145780.py:46: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[col + '_Encoded'].fillna(y_train.mean(), inplace=True)
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\3721145780.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[col + '_Encoded'].fillna(y_train.mean(), inplace=True)
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\3721145780.py:46: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[col + '_Encoded'].fillna(y_train.mean(), inplace=True)
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\3721145780.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[col + '_Encoded'].fillna(y_train.mean(), inplace=True)
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\3721145780.py:46: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[col + '_Encoded'].fillna(y_train.mean(), inplace=True)
C:\Users\musta\AppData\Local\Temp\ipykernel_33436\3721145780.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[col + '_Encoded'].fillna(y_train.mean(), inplace=True)

Başarı Skoru (R2): %60.14
Ortalama Hata (MAE): 135,386 TL