In [5]:
import numpy as np
import pandas as pd

In [6]:
#random seed

np.random.seed(42)

set1no = 900
set2no = 100

In [7]:
df1 = pd.DataFrame({
    "feature_1":np.random.normal(loc=0,scale=1,size=set1no),
    "feature_2":np.random.normal(loc=0,scale=1,size=set1no),
    "target":[0] * set1no})
df2 = pd.DataFrame({
    "feature_1":np.random.normal(loc=0,scale=1,size=set2no),
    "feature_2":np.random.normal(loc=0,scale=1,size=set2no),
    "target":[1] * set2no})

In [8]:
df = pd.concat([df1,df2]).reset_index(drop=True)

In [9]:
df

     feature_1  feature_2  target
0     0.496714   0.368673       0
1    -0.138264  -0.393339       0
2     0.647689   0.028745       0
3     1.523030   1.278452       0
4    -0.234153   0.191099       0
..         ...        ...     ...
995  -0.370011   1.070150       1
996  -0.258796  -0.026521       1
997   1.598647  -0.881875       1
998   0.560919  -0.163067       1
999  -0.295480  -0.744903       1

[1000 rows x 3 columns]

In [10]:
 #upsampling -> upsample minority

In [11]:
#downsampling -> downsample majority

In [12]:
#upsampling

In [13]:
df_minority = df[df["target"] == 1]
df_minority

     feature_1  feature_2  target
900   1.901191   0.696954       1
901  -0.060661  -0.333819       1
902  -0.708407   1.173125       1
903  -1.513714   0.369642       1
904  -1.803140  -0.107302       1
..         ...        ...     ...
995  -0.370011   1.070150       1
996  -0.258796  -0.026521       1
997   1.598647  -0.881875       1
998   0.560919  -0.163067       1
999  -0.295480  -0.744903       1

[100 rows x 3 columns]

In [14]:
df_majority = df[df["target"] == 0]
df_majority

     feature_1  feature_2  target
0     0.496714   0.368673       0
1    -0.138264  -0.393339       0
2     0.647689   0.028745       0
3     1.523030   1.278452       0
4    -0.234153   0.191099       0
..         ...        ...     ...
895   0.648710  -0.751969       0
896  -0.167118  -0.319054       0
897   0.146714  -0.796026       0
898   1.206509   1.076007       0
899  -0.816936   0.021312       0

[900 rows x 3 columns]

In [15]:
from sklearn.utils import resample

In [19]:
df_minority_upsampled = resample(df_minority,replace=True,n_samples=len(df_majority),random_state=42)

In [20]:
df_minority_upsampled.shape

(900, 3)

In [21]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled])

In [22]:
df_upsampled["target"].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [23]:
df_majority_upsampled = resample(df_majority,replace=True,n_samples=len(df_minority),random_state=42)

In [24]:
df_downsampled = pd.concat([df_minority,df_majority_upsampled])

In [25]:
df_downsampled["target"].value_counts()

target
1    100
0    100
Name: count, dtype: int64

In [26]:
!pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Requirement already satisfied: imbalanced-learn in d:\anaconda\lib\site-packages (from imblearn) (0.13.0)
Requirement already satisfied: numpy<3,>=1.24.3 in d:\anaconda\lib\site-packages (from imbalanced-learn->imblearn) (2.1.3)
Requirement already satisfied: scipy<2,>=1.10.1 in d:\anaconda\lib\site-packages (from imbalanced-learn->imblearn) (1.15.3)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in d:\anaconda\lib\site-packages (from imbalanced-learn->imblearn) (1.6.1)
Requirement already satisfied: sklearn-compat<1,>=0.1 in d:\anaconda\lib\site-packages (from imbalanced-learn->imblearn) (0.1.3)
Requirement already satisfied: joblib<2,>=1.1.1 in d:\anaconda\lib\site-packages (from imbalanced-learn->imblearn) (1.4.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in d:\anaconda\lib\site-packages (from imbalanced-learn->imblearn) (3.5.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Installing collected packages: imblearn
Successfully installed imblearn-0.0

In [27]:
from imblearn.over_sampling import SMOTE

In [28]:
oversample = SMOTE()

In [30]:
(X,y) = oversample.fit_resample(df[["feature_1","feature_2"]],df["target"])
X

      feature_1  feature_2
0      0.496714   0.368673
1     -0.138264  -0.393339
2      0.647689   0.028745
3      1.523030   1.278452
4     -0.234153   0.191099
...         ...        ...
1795   0.701868  -0.173309
1796   1.545917  -1.335943
1797   1.358114  -0.225781
1798   0.486916  -0.147628
1799   0.504733  -1.114370

[1800 rows x 2 columns]

In [31]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1795    1
1796    1
1797    1
1798    1
1799    1
Name: target, Length: 1800, dtype: int64

In [32]:
oversample_df = pd.concat([X,y],axis=1)

In [34]:
oversample_df["target"].value_counts()

target
0    900
1    900
Name: count, dtype: int64